use chrono::Utc;

use crate::models::*;

pub(super) struct DefaultVendor {
    id: String,
    name: String,
    backup_command: String,
    ssh_port: i32,
    mac_prefixes: Vec<String>,
    vendor_class: String,
    default_template: String,
}

pub(super) fn get_default_vendors_internal() -> Vec<DefaultVendor> {
    vec![
        DefaultVendor {
            id: "opengear".to_string(),
            name: "OpenGear".to_string(),
            backup_command: "config export".to_string(),
            ssh_port: 22,
            mac_prefixes: vec!["00:13:C6".to_string()],
            vendor_class: "OpenGear".to_string(),
            default_template: "opengear-lighthouse".to_string(),
        },
        DefaultVendor {
            id: "cisco".to_string(),
            name: "Cisco".to_string(),
            backup_command: "show running-config".to_string(),
            ssh_port: 22,
            mac_prefixes: vec![
                "00:00:0C".to_string(), "00:1A:2F".to_string(), "00:1B:0D".to_string(),
                "00:1C:0E".to_string(), "00:1D:45".to_string(), "00:22:55".to_string(),
                "00:26:99".to_string(), "2C:31:24".to_string(), "64:F6:9D".to_string(),
                "F8:C2:88".to_string(),
            ],
            vendor_class: "Cisco Systems, Inc.".to_string(),
            default_template: "cisco-ios".to_string(),
        },
        DefaultVendor {
            id: "arista".to_string(),
            name: "Arista".to_string(),
            backup_command: "show running-config".to_string(),
            ssh_port: 22,
            mac_prefixes: vec![
                "00:1C:73".to_string(), "28:99:3A".to_string(), "44:4C:A8".to_string(),
                "50:01:00".to_string(), "74:83:C2".to_string(),
            ],
            vendor_class: "Arista Networks".to_string(),
            default_template: "arista-eos".to_string(),
        },
        DefaultVendor {
            id: "juniper".to_string(),
            name: "Juniper".to_string(),
            backup_command: "show configuration | display set".to_string(),
            ssh_port: 22,
            mac_prefixes: vec![
                "00:05:85".to_string(), "00:10:DB".to_string(), "00:12:1E".to_string(),
                "00:14:F6".to_string(), "00:17:CB".to_string(), "00:19:E2".to_string(),
                "00:21:59".to_string(), "00:23:9C".to_string(), "00:26:88".to_string(),
                "2C:6B:F5".to_string(), "3C:61:04".to_string(), "50:C7:09".to_string(),
                "78:FE:3D".to_string(), "84:B5:9C".to_string(), "AC:4B:C8".to_string(),
                "F4:B5:2F".to_string(), "F8:C0:01".to_string(),
            ],
            vendor_class: "Juniper Networks".to_string(),
            default_template: "juniper-junos".to_string(),
        },
        DefaultVendor {
            id: "raspberry-pi".to_string(),
            name: "Raspberry Pi".to_string(),
            backup_command: "cat /etc/network/interfaces".to_string(),
            ssh_port: 22,
            mac_prefixes: vec![
                "B8:27:EB".to_string(), "DC:A6:32".to_string(), "E4:5F:01".to_string(),
                "D8:3A:DD".to_string(), "28:CD:C1".to_string(),
            ],
            vendor_class: "Raspberry Pi".to_string(),
            default_template: "raspberry-pi".to_string(),
        },
        DefaultVendor {
            id: "frr".to_string(),
            name: "FRRouting".to_string(),
            backup_command: "vtysh -c 'show running-config'".to_string(),
            ssh_port: 22,
            mac_prefixes: vec![],
            vendor_class: "FRRouting".to_string(),
            default_template: "frr-bgp".to_string(),
        },
        DefaultVendor {
            id: "gobgp".to_string(),
            name: "GoBGP".to_string(),
            backup_command: "gobgp global; echo '---'; gobgp neighbor".to_string(),
            ssh_port: 22,
            mac_prefixes: vec![],
            vendor_class: "GoBGP".to_string(),
            default_template: "gobgp-bgp".to_string(),
        },
    ]
}

fn get_default_templates_internal() -> Vec<DefaultTemplate> {
    vec![
        DefaultTemplate {
            id: "cisco-ios".to_string(),
            name: "Cisco IOS Default".to_string(),
            description: "Basic Cisco IOS configuration with SSH and management".to_string(),
            vendor_id: "cisco".to_string(),
            content: r#"! ZTP Configuration for {{Hostname}}
! Generated by ZTP Server
! MAC: {{MAC}}
! IP: {{IP}}
!
hostname {{Hostname}}
!
no ip domain-lookup
ip domain-name local
!
interface Vlan1
 description Management Interface
 ip address {{IP}} {{Subnet}}
 no shutdown
!
ip default-gateway {{Gateway}}
!
username admin privilege 15 secret admin
!
line console 0
 logging synchronous
!
line vty 0 4
 login local
 transport input ssh
 exec-timeout 30 0
!
crypto key generate rsa modulus 2048
ip ssh version 2
!
end"#.to_string(),
        },
        DefaultTemplate {
            id: "arista-eos".to_string(),
            name: "Arista EOS Default".to_string(),
            description: "Basic Arista EOS configuration with SSH and management".to_string(),
            vendor_id: "arista".to_string(),
            content: r#"! ZTP Configuration for {{Hostname}}
! Generated by ZTP Server
! MAC: {{MAC}}
! IP: {{IP}}
!
hostname {{Hostname}}
!
username admin privilege 15 role network-admin secret admin
!
interface Management1
   description Management Interface
   ip address {{IP}}/24
   no shutdown
!
ip route 0.0.0.0/0 {{Gateway}}
!
management api http-commands
   protocol https
   no shutdown
!
management ssh
   idle-timeout 30
   no shutdown
!
end"#.to_string(),
        },
        DefaultTemplate {
            id: "juniper-junos".to_string(),
            name: "Juniper Junos Default".to_string(),
            description: "Basic Juniper Junos configuration with SSH and management".to_string(),
            vendor_id: "juniper".to_string(),
            content: r#"## ZTP Configuration for {{Hostname}}
## Generated by ZTP Server
## MAC: {{MAC}}
## IP: {{IP}}

system {
    host-name {{Hostname}};
    root-authentication {
        encrypted-password "$6$admin";
    }
    login {
        user admin {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$6$admin";
            }
        }
    }
    services {
        ssh {
            root-login allow;
        }
        netconf {
            ssh;
        }
    }
}

interfaces {
    em0 {
        unit 0 {
            family inet {
                address {{IP}}/24;
            }
        }
    }
}

routing-options {
    static {
        route 0.0.0.0/0 next-hop {{Gateway}};
    }
}"#.to_string(),
        },
        DefaultTemplate {
            id: "opengear-lighthouse".to_string(),
            name: "OpenGear Lighthouse Enrollment".to_string(),
            description: "OpenGear OM device configuration for Lighthouse enrollment".to_string(),
            vendor_id: "opengear".to_string(),
            content: r#"# ZTP Configuration for {{Hostname}}
# Generated by ZTP Server
# MAC: {{MAC}}
# IP: {{IP}}

config.system.name={{Hostname}}
config.interfaces.wan.mode=static
config.interfaces.wan.address={{IP}}
config.interfaces.wan.netmask={{Subnet}}
config.interfaces.wan.gateway={{Gateway}}

# SSH access
config.services.ssh.enable=on

# Web interface
config.services.webui.enable=on"#.to_string(),
        },
        DefaultTemplate {
            id: "frr-bgp".to_string(),
            name: "FRR BGP Default".to_string(),
            description: "FRRouting configuration with BGP and management interface".to_string(),
            vendor_id: "frr".to_string(),
            content: r#"! ZTP Configuration for {{Hostname}}
! Generated by ZTP Server
! MAC: {{MAC}}
! IP: {{IP}}
!
frr defaults traditional
hostname {{Hostname}}
log file /var/log/frr/frr.log
service integrated-vtysh-config
!
interface eth0
 description Management Interface
 ip address {{IP}}/24
!
ip route 0.0.0.0/0 {{Gateway}}
!
router bgp 65000
 bgp router-id {{IP}}
 no bgp ebgp-requires-policy
 !
 address-family ipv4 unicast
 exit-address-family
!
end"#.to_string(),
        },
        DefaultTemplate {
            id: "gobgp-bgp".to_string(),
            name: "GoBGP BGP Default".to_string(),
            description: "GoBGP YAML configuration with BGP global settings".to_string(),
            vendor_id: "gobgp".to_string(),
            content: r#"# ZTP Configuration for {{Hostname}}
# Generated by ZTP Server
# MAC: {{MAC}}
# IP: {{IP}}

global:
  config:
    as: 65000
    router-id: {{IP}}
    port: 179"#.to_string(),
        },
        DefaultTemplate {
            id: "generic-switch".to_string(),
            name: "Generic Switch Template".to_string(),
            description: "A generic template suitable for most network switches".to_string(),
            vendor_id: "".to_string(),
            content: r#"! ZTP Configuration for {{Hostname}}
! Generated by ZTP Server
! MAC: {{MAC}}
! IP: {{IP}}
!
hostname {{Hostname}}
!
interface Vlan1
 ip address {{IP}} {{Subnet}}
 no shutdown
!
ip default-gateway {{Gateway}}
!
username admin privilege 15 secret admin
!
line vty 0 4
 login local
 transport input ssh
!
end"#.to_string(),
        },
    ]
}

struct DefaultTemplate {
    id: String,
    name: String,
    description: String,
    vendor_id: String,
    content: String,
}

struct DefaultDhcpOption {
    id: String,
    option_number: i32,
    name: String,
    value: String,
    option_type: String,
    vendor_id: String,
    description: String,
    enabled: bool,
}

fn get_default_dhcp_options_internal() -> Vec<DefaultDhcpOption> {
    vec![
        DefaultDhcpOption {
            id: "tftp-server".to_string(),
            option_number: 66,
            name: "TFTP Server".to_string(),
            value: "${tftp_server_ip}".to_string(),
            option_type: "ip".to_string(),
            vendor_id: "".to_string(),
            description: "TFTP server for config files".to_string(),
            enabled: true,
        },
        DefaultDhcpOption {
            id: "tftp-cisco-150".to_string(),
            option_number: 150,
            name: "Cisco TFTP (Option 150)".to_string(),
            value: "${tftp_server_ip}".to_string(),
            option_type: "ip".to_string(),
            vendor_id: "cisco".to_string(),
            description: "Cisco-specific TFTP server option".to_string(),
            enabled: true,
        },
        DefaultDhcpOption {
            id: "bootfile-cisco".to_string(),
            option_number: 67,
            name: "Cisco Bootfile".to_string(),
            value: "network-confg".to_string(),
            option_type: "string".to_string(),
            vendor_id: "cisco".to_string(),
            description: "Cisco IOS config filename".to_string(),
            enabled: true,
        },
        DefaultDhcpOption {
            id: "bootfile-arista".to_string(),
            option_number: 67,
            name: "Arista Bootfile".to_string(),
            value: "startup-config".to_string(),
            option_type: "string".to_string(),
            vendor_id: "arista".to_string(),
            description: "Arista EOS config filename".to_string(),
            enabled: true,
        },
        DefaultDhcpOption {
            id: "bootfile-juniper".to_string(),
            option_number: 67,
            name: "Juniper Bootfile".to_string(),
            value: "juniper.conf".to_string(),
            option_type: "string".to_string(),
            vendor_id: "juniper".to_string(),
            description: "Juniper config filename".to_string(),
            enabled: true,
        },
        DefaultDhcpOption {
            id: "bootfile-frr".to_string(),
            option_number: 67,
            name: "FRR Bootfile".to_string(),
            value: "frr.conf".to_string(),
            option_type: "string".to_string(),
            vendor_id: "frr".to_string(),
            description: "FRRouting config filename".to_string(),
            enabled: true,
        },
        DefaultDhcpOption {
            id: "bootfile-gobgp".to_string(),
            option_number: 67,
            name: "GoBGP Bootfile".to_string(),
            value: "gobgpd.conf".to_string(),
            option_type: "string".to_string(),
            vendor_id: "gobgp".to_string(),
            description: "GoBGP YAML config filename".to_string(),
            enabled: true,
        },
        DefaultDhcpOption {
            id: "opengear-ztp".to_string(),
            option_number: 43,
            name: "OpenGear ZTP".to_string(),
            value: "".to_string(),
            option_type: "hex".to_string(),
            vendor_id: "opengear".to_string(),
            description: "OpenGear vendor-specific enrollment options".to_string(),
            enabled: false,
        },
    ]
}

/// Seed data helpers used by the Store during migration

pub(super) fn seed_vendor_params() -> Vec<(String, String, String, i32, String, String, String)> {
    get_default_vendors_internal()
        .into_iter()
        .map(|v| {
            let mac_json = serde_json::to_string(&v.mac_prefixes).unwrap_or_else(|_| "[]".to_string());
            (v.id, v.name, v.backup_command, v.ssh_port, mac_json, v.vendor_class, v.default_template)
        })
        .collect()
}

pub(super) fn seed_template_params() -> Vec<(String, String, String, String, String)> {
    get_default_templates_internal()
        .into_iter()
        .map(|t| (t.id, t.name, t.description, t.vendor_id, t.content))
        .collect()
}

pub(super) fn seed_dhcp_option_params() -> Vec<(String, i32, String, String, String, String, String, bool)> {
    get_default_dhcp_options_internal()
        .into_iter()
        .map(|o| (o.id, o.option_number, o.name, o.value, o.option_type, o.vendor_id, o.description, o.enabled))
        .collect()
}

/// Get default vendors as models (for API)
pub fn get_default_vendors_models() -> Vec<Vendor> {
    let now = Utc::now();
    get_default_vendors_internal()
        .into_iter()
        .map(|v| Vendor {
            id: v.id,
            name: v.name,
            backup_command: v.backup_command,
            deploy_command: String::new(),
            ssh_port: v.ssh_port,
            ssh_user: None,
            ssh_pass: None,
            mac_prefixes: v.mac_prefixes,
            vendor_class: v.vendor_class,
            default_template: v.default_template,
            device_count: None,
            created_at: now,
            updated_at: now,
        })
        .collect()
}

/// Get default DHCP options as models (for API)
pub fn get_default_dhcp_options_models() -> Vec<DhcpOption> {
    let now = Utc::now();
    get_default_dhcp_options_internal()
        .into_iter()
        .map(|o| DhcpOption {
            id: o.id,
            option_number: o.option_number,
            name: o.name,
            value: o.value,
            option_type: o.option_type,
            vendor_id: if o.vendor_id.is_empty() { None } else { Some(o.vendor_id) },
            description: if o.description.is_empty() { None } else { Some(o.description) },
            enabled: o.enabled,
            created_at: now,
            updated_at: now,
        })
        .collect()
}
