// Core module - platform agnostic code
// This can be shared between React Web and React Native

// Types
export * from './types';

// Services
export {
  AuthService,
  BaseService,
  DeviceService,
  SettingsService,
  IpamService,
  DeviceModelService,
  PortAssignmentService,
  JobTemplateService,
  CredentialService,
  OutputParserService,
  DeviceRoleService,
  NetBoxService,
  configureServices,
  getServiceConfig,
  getInflightCount,
  onInflightChange,
  getApiHistory,
  clearApiHistory,
  onApiHistoryChange,
  checkApiHealth,
  getServices,
  getWebSocketService,
  WebSocketService,
  type ServiceConfig,
  type Services,
  type WebSocketEvent,
  type WebSocketEventType,
  type DeviceDiscoveredPayload,
  type WebSocketEventHandler,
  type ConnectResult,
  type ConfigResult,
  type ApiHistoryEntry,
  type BackupContentResult,
  type ConfigPreviewResult,
  type DeployConfigResult,
  type PingResult,
  type SSHResult,
  type NetBoxConfig,
  type NetBoxStatus,
  type NetBoxSyncResult,
  type NetBoxManufacturer,
  type NetBoxSite,
  type NetBoxDeviceRole,
  type NetBoxDevice,
  type DetectedVariable,
  type TemplatizeResponse,
  trackEvent,
  getTelemetryEvents,
  clearTelemetryEvents,
  onTelemetryChange,
  initTelemetry,
  type TelemetryEvent,
  type TelemetryEventType,
  addNotification,
  markAllRead,
  clearNotifications,
  getNotifications,
  getUnreadCount,
  onNotificationsChange,
  type Notification,
  type NotificationAction,
  type NotificationLevel,
  navigateTo,
  navigateAction,
  registerNavigator,
  type NavigationTarget,
  type LoginRequest,
  type LoginResponse,
  getTokenStorage,
  setTokenStorage,
  type TokenStorage,
} from './services';

// Hooks
export {
  useAuth,
  useAuthState,
  AuthProvider,
  type UseAuthReturn,
  useDevices,
  useSettings,
  useBackups,
  useVendors,
  useDhcpOptions,
  useTemplates,
  useDiscovery,
  useTestContainers,
  useTheme,
  useWebTheme,
  useForm,
  useWebSocket,
  useModalForm,
  useNotification,
  createMobileNotificationHandler,
  createWebNotificationHandler,
  useListFiltering,
  useAsyncModal,
  useSimpleModal,
  useLocalSettings,
  useLocalAddresses,
  useInflight,
  useApiHistory,
  useModalRoute,
  useLocalStorage,
  useNavigationTab,
  usePersistedTab,
  usePersistedSet,
  useTelemetry,
  useTableFeatures,
  type ColumnFilterDef,
  useNotificationHistory,
  useVendorActions,
  type UseVendorActionsOptions,
  type UseVendorActionsReturn,
  useJobs,
  type UseJobsOptions,
  type UseJobsReturn,
  useTopologies,
  type UseTopologiesOptions,
  type UseTopologiesReturn,
  useDeviceVariables,
  type UseDeviceVariablesOptions,
  type UseDeviceVariablesReturn,
  useGroups,
  type UseGroupsOptions,
  type UseGroupsReturn,
  useResolvedVariables,
  type UseResolvedVariablesReturn,
  useIpam,
  type UseIpamOptions,
  type UseIpamReturn,
  useDeviceModels,
  type UseDeviceModelsOptions,
  type UseDeviceModelsReturn,
  usePortAssignments,
  type UsePortAssignmentsReturn,
  useJobTemplates,
  type UseJobTemplatesReturn,
  useCredentials,
  type UseCredentialsOptions,
  type UseCredentialsReturn,
  useOutputParsers,
  type UseOutputParsersReturn,
  useDeviceRoles,
  type UseDeviceRolesReturn,
  useUsers,
  type UseUsersReturn,
  getLocalApiUrl,
  setLocalApiUrl,
  getDefaultPageSize,
  getTablePageSize,
  setTablePageSize,
  clearTablePageSizeOverrides,
  THEME_OPTIONS,
  type UseDevicesOptions,
  type UseDevicesReturn,
  type UseSettingsReturn,
  type UseBackupsReturn,
  type UseVendorsOptions,
  type UseVendorsReturn,
  type UseDhcpOptionsOptions,
  type UseDhcpOptionsReturn,
  type UseTemplatesOptions,
  type UseTemplatesReturn,
  type UseDiscoveryOptions,
  type UseDiscoveryReturn,
  type UseTestContainersOptions,
  type UseTestContainersReturn,
  type ThemeConfig,
  type UseThemeOptions,
  type UseThemeReturn,
  type UseFormOptions,
  type UseFormReturn,
  type UseWebSocketOptions,
  type UseWebSocketReturn,
  type UseModalFormOptions,
  type UseModalFormReturn,
  type NotificationType,
  type NotificationMessage,
  type ConfirmOptions,
  type NotificationHandler,
  type UseNotificationOptions,
  type UseNotificationReturn,
  type UseListFilteringOptions,
  type UseListFilteringReturn,
  type GroupedItems,
  type UseAsyncModalOptions,
  type UseAsyncModalReturn,
  type LocalSettings,
  type UseLocalSettingsReturn,
  type UseLocalAddressesReturn,
  type UseModalRouteReturn,
} from './hooks';

// Utils
export {
  formatDate,
  formatRelativeTime,
  formatMacAddress,
  formatFileSize,
  formatExpiry,
  formatEventType,
  getEventTypeIcon,
  validateMacAddress,
  validateIpAddress,
  validateIpv4,
  validateIpv6,
  validatePrefix,
  validateHostname,
  validateDeviceForm,
  validateSettingsForm,
  validators,
  getErrorMessage,
  parseApiError,
  lookupVendorByMac,
  setVendorCache,
  getVendorCache,
  randomHex,
  generateMac,
  getVendorPrefixOptions,
  getVendorClassForVendor,
  getVendorFilterOptions,
  getVendorSelectOptions,
  getVendorName,
  groupByVendor,
  filterByVendor,
  generateId,
  slugify,
  createChangeHandler,
  parseListValue,
  formatListValue,
  getStatusColor,
  getStatusColors,
  getVariableTypeIcon,
  getVariableTypeColor,
  getStatusIcon,
  getStatusLabel,
  getJobTypeBadgeVariant,
  getCredTypeBadgeVariant,
  getHttpMethodBadgeVariant,
  getActionTypeBadgeVariant,
  type BadgeVariant,
  type Validator,
  type ValidationResult,
  type ParsedApiError,
  type DiscoveryEventType,
  type VendorPrefixOption,
  type VendorFilterOption,
  type VendorSelectOption,
  type GroupedByVendor,
  type VariableTypeIcon,
  type StatusIcon,
  countDevicesByStatus,
  countRecentBackups,
  getRecentJobs,
  resolveVendor,
  createDeviceFromDiscovery,
  autoDetectVendorFromMac,
  autoSelectTemplateForVendor,
  getDhcpInfoItems,
  getDhcpDetailFields,
  isPatchPanel,
  buildPortAssignmentMap,
  buildDeviceOptions,
  buildPortOptionsFromModel,
  buildPatchPanelOptions,
  findDeviceModel,
  countModelPorts,
  countAssignedPorts,
  type SelectOption,
} from './utils';

// Constants
export {
  DEFAULT_DHCP_OPTIONS,
  DHCP_OPTION_TYPES,
  EMPTY_VENDOR_FORM,
  EMPTY_VENDOR_ACTION_FORM,
  EMPTY_DHCP_OPTION_FORM,
  EMPTY_TEMPLATE_FORM,
  EMPTY_TOPOLOGY_FORM,
  TOPOLOGY_ROLE_OPTIONS,
  SAMPLE_DEVICE_FOR_PREVIEW,
  VENDOR_CLASS_OPTIONS,
  CONFIG_METHOD_OPTIONS,
  SWITCH_MODELS,
  getChassisLayout,
  getVendorModels,
  getAllChassisLayouts,
  CONNECTOR_WIDTHS,
  SPEED_COLOR_NAMES,
  getConnectorWidth,
  getSpeedColorName,
} from './constants';

// Store
export { store, type RootState, type AppDispatch, useAppDispatch, useAppSelector } from './store';

// Theme
export {
  darkTheme,
  lightTheme,
  plainTheme,
  solarizedTheme,
  draculaTheme,
  nordTheme,
  evergreenDarkTheme,
  evergreenLightTheme,
  oceanDarkTheme,
  oceanLightTheme,
  themes,
  getThemeColors,
  MONOSPACE_FONT,
  FONT_SIZES,
  type ThemeColors,
  type FontSize,
} from './theme';
